exp_name: 'Pretrain_ImageNet'
scale : 4
PATH: './Data/'
num_workers: 1
train:
  batch_size: 4
  epochs: 100
  d_lr: 0.0001
  g_lr: 0.0001
  d_beta: 0.9
  g_beta: 0.9
  d_optimizer_step_size:
  g_optimizer_step_size:
  d_optimizer_gamma:
  g_optimizer_gamma:
val:
  batch_size: 1