exp_name: 'Pretrain_ImageNet'
scale : 4
PATH: './Data/'
MODEL_SAVE_LOCATION: './saved_models/ImageNet/' 
num_workers: 1
visualize_location: './Tensorboard/'
model:
  block_depth: 7
  pixel_weight : 1.0
  content_weight : 1.0
  adverserial_weight : 0.001
train:
  batch_size: 4
  epochs: 100
  d_lr: 0.0001
  g_lr: 0.0001
  d_beta: 0.9
  g_beta: 0.9
  d_optimizer_step_size: 0.9
  g_optimizer_step_size: 0.9
  d_optimizer_gamma: 0.1
  g_optimizer_gamma: 0.1
val:
  batch_size: 1